name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # substitua pelo nome do seu branch principal
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          # Comandos para construir seu site, se necessário
          # ...

          # Copiar o arquivo .htaccess
          cp .htaccess ./build/.htaccess

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # substitua pelo diretório de publicação do seu site
